POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "lasang@cat.us",
    "password": "123oui",
    "pseudo": "Garfel",
    "bio": "Gourmand",
    "token": "B"
}
###
GET http://localhost:5000/api/utilisateur
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwicHNldWRvIjoiR2FyZmVsIiwiZW1haWwiOiJsYXNhbmdAY2F0LnVzIiwiaWF0IjoxNjY0NTI5ODMzLCJleHAiOjE2NjQ1MzEwMzN9.HNmxd9jAsgjVGd6kcnM42Ne8o1zjwq8dJDzwUSAXFp0

###
GET http://localhost:5000/api/auth/refresh_token